-- Seed published executive-search opportunities (idempotent by slug)

insert into public.jobs (
  slug,
  title,
  description,
  location,
  employment_type,
  department,
  industry,
  work_mode,
  experience_level,
  salary_min,
  salary_max,
  salary_currency,
  status,
  published_at
)
values
  (
    'chief-financial-officer-industrial-group',
    'Chief Financial Officer — Industrial Conglomerate',
    E'Retained search for a CFO to partner with the promoter board of a diversified industrial group.\n\nMandate:\n• Lead FP&A, treasury, and statutory reporting for listed and unlisted entities\n• Drive working-capital discipline and investor communications\n• Build a high-trust finance leadership team across NCR\n\nIdeal profile: Big-4 or listed-industry CFO experience, 18+ years, calm under board scrutiny.',
    'Noida / Delhi NCR',
    'Full-time',
    'Finance',
    'Industrial & Manufacturing',
    'hybrid',
    'executive',
    8500000,
    12000000,
    'INR',
    'published',
    timezone('utc', now())
  ),
  (
    'vp-manufacturing-automotive-components',
    'VP Manufacturing — Automotive Components',
    E'Mumbai-based leadership role for a precision manufacturing business supplying OEMs.\n\nScope includes plant productivity, EHS, capex execution, and supplier quality partnerships.\n\nRequires prior P&L or large plant leadership in automotive or engineering sectors.',
    'Mumbai',
    'Full-time',
    'Operations',
    'Automotive',
    'onsite',
    'executive',
    6500000,
    9500000,
    'INR',
    'published',
    timezone('utc', now())
  ),
  (
    'head-hr-transformation-chennai',
    'Head HR — Business Transformation',
    E'Chennai HQ role to lead HR for a multi-location services organisation undergoing operating-model change.\n\nFocus: leadership assessment, compensation architecture, culture programmes, and HRIS maturity.\n\nCHRO track record in mid-to-large Indian corporates preferred.',
    'Chennai',
    'Full-time',
    'Human Resources',
    'Professional Services',
    'hybrid',
    'executive',
    5500000,
    8000000,
    'INR',
    'published',
    timezone('utc', now())
  ),
  (
    'general-manager-supply-chain',
    'General Manager — Supply Chain & Logistics',
    E'Pan-India supply chain mandate for a consumer and industrial products company.\n\nEnd-to-end responsibility for demand planning, warehousing network, and 3PL governance.\n\nSeeking 15+ years including senior leadership in SCM or logistics.',
    'Noida',
    'Full-time',
    'Supply Chain',
    'FMCG & Distribution',
    'hybrid',
    'lead',
    4500000,
    7000000,
    'INR',
    'published',
    timezone('utc', now())
  ),
  (
    'director-enterprise-sales-b2b',
    'Director — Enterprise Sales (B2B)',
    E'Revenue leadership role for a technology-enabled B2B platform scaling across India.\n\nOwn key account strategy, enterprise pipeline, and hunter-led team building.\n\nPrior experience selling to CIO/CFO buyers in banking, insurance, or manufacturing is valued.',
    'Mumbai / Bengaluru',
    'Full-time',
    'Sales',
    'Technology',
    'remote',
    'lead',
    5000000,
    8500000,
    'INR',
    'published',
    timezone('utc', now())
  ),
  (
    'ceo-portfolio-healthcare-services',
    'CEO — Portfolio Company (Healthcare Services)',
    E'Board-backed CEO search for a healthcare services platform in growth phase.\n\nMandate covers P&L ownership, clinical partnerships, regulatory compliance, and capital efficiency.\n\nPrior CEO/ BU head experience in hospitals, diagnostics, or healthcare services required.',
    'Chennai / Hyderabad',
    'Full-time',
    'General Management',
    'Healthcare',
    'hybrid',
    'executive',
    10000000,
    18000000,
    'INR',
    'published',
    timezone('utc', now())
  )
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  location = excluded.location,
  employment_type = excluded.employment_type,
  department = excluded.department,
  industry = excluded.industry,
  work_mode = excluded.work_mode,
  experience_level = excluded.experience_level,
  salary_min = excluded.salary_min,
  salary_max = excluded.salary_max,
  salary_currency = excluded.salary_currency,
  status = excluded.status,
  published_at = coalesce(public.jobs.published_at, excluded.published_at),
  updated_at = timezone('utc', now());
